# Generated by Django 4.2.7 on 2023-12-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_rupt',
            field=models.BooleanField(default=False),
        ),
    ]
